# Generated by Django 5.2.2 on 2025-06-06 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtributoGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Atributo da Grade',
                'verbose_name_plural': 'Atributos da Grade',
            },
        ),
        migrations.CreateModel(
            name='FichaTecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(help_text='Ex: Ficha Padrão V1.0', max_length=255)),
            ],
            options={
                'verbose_name': 'Ficha Técnica',
                'verbose_name_plural': 'Fichas Técnicas',
            },
        ),
        migrations.CreateModel(
            name='ProdutoModelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_modelo', models.CharField(help_text='Referência principal do modelo', max_length=50, unique=True)),
                ('nome_modelo', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Modelo de Produto',
                'verbose_name_plural': 'Modelos de Produto',
                'ordering': ['nome_modelo'],
            },
        ),
        migrations.CreateModel(
            name='ItemFichaTecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=4, help_text='Quantidade necessária para 1 unidade do produto', max_digits=10)),
                ('ficha_tecnica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.fichatecnica')),
                ('materia_prima', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produtos.materiaprima')),
            ],
            options={
                'verbose_name': 'Item da Ficha Técnica',
                'verbose_name_plural': 'Itens da Ficha Técnica',
                'unique_together': {('ficha_tecnica', 'materia_prima')},
            },
        ),
        migrations.AddField(
            model_name='fichatecnica',
            name='materias_primas',
            field=models.ManyToManyField(related_name='fichas_tecnicas', through='produtos.ItemFichaTecnica', to='produtos.materiaprima'),
        ),
        migrations.AddField(
            model_name='fichatecnica',
            name='produto_modelo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ficha_tecnica', to='produtos.produtomodelo'),
        ),
        migrations.CreateModel(
            name='ValorAtributoGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=50)),
                ('atributo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores', to='produtos.atributograde')),
            ],
            options={
                'verbose_name': 'Valor de Atributo',
                'verbose_name_plural': 'Valores de Atributos',
                'unique_together': {('atributo', 'valor')},
            },
        ),
        migrations.CreateModel(
            name='ProdutoVariacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(help_text='SKU único para esta variação específica', max_length=100, unique=True)),
                ('codigo_barras', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('preco_venda', models.DecimalField(decimal_places=2, max_digits=10)),
                ('saldo_em_estoque', models.IntegerField(default=0)),
                ('produto_modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variacoes', to='produtos.produtomodelo')),
                ('valores_atributos', models.ManyToManyField(related_name='variacoes', to='produtos.valoratributograde')),
            ],
            options={
                'verbose_name': 'Variação de Produto (SKU)',
                'verbose_name_plural': 'Variações de Produto (SKUs)',
                'ordering': ['produto_modelo__nome_modelo', 'sku'],
            },
        ),
    ]
