# Generated by Django 5.2.2 on 2025-06-06 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produtos', '0002_atributograde_fichatecnica_produtomodelo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemProducao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_op', models.CharField(help_text='Número único da Ordem de Produção', max_length=50, unique=True)),
                ('quantidade_a_produzir', models.PositiveIntegerField()),
                ('data_emissao', models.DateTimeField(auto_now_add=True)),
                ('data_previsao_inicio', models.DateField()),
                ('data_previsao_termino', models.DateField()),
                ('data_inicio_real', models.DateTimeField(blank=True, null=True)),
                ('data_termino_real', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PLANEJADA', 'Planejada'), ('LIBERADA', 'Liberada para Produção'), ('EM_PRODUCAO', 'Em Produção'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada')], default='PLANEJADA', max_length=20)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('produto_variacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordens_de_producao', to='produtos.produtovariacao')),
            ],
            options={
                'verbose_name': 'Ordem de Produção',
                'verbose_name_plural': 'Ordens de Produção',
                'ordering': ['-data_emissao'],
            },
        ),
    ]
